import type { Metadata } from "next"
import { Open_Sans } from "next/font/google"
import Providers from "@/app/contexts"
import "./globals.css"

const openSans = Open_Sans({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Streak App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <Providers>{children} </Providers>
      </body>
    </html>
  )
}
